[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sparkdq"
version = "0.1.0"
dependencies = [
    "pyspark>=3.3.0",
    "delta-spark>=2.3.0",
    "spark-expectations>=2.5.0",
]